# Generated by Django 3.1 on 2020-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200924_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(default='todo'),
            preserve_default=False,
        ),
    ]
